/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./templates/**/*.html"],
  safelist: [
    // Spacing
    "gap-0", "gap-0.5", "gap-1", "gap-1.5", "gap-2", "gap-2.5", "gap-3", "gap-4", "gap-5", "gap-6",
    "gap-8", "gap-10", "gap-12",
    "p-0", "p-0.5", "p-1", "p-1.5", "p-2", "p-2.5", "p-3", "p-4", "p-5", "p-6", "p-8", "p-12",
    "px-0", "px-0.5", "px-1", "px-1.5", "px-2", "px-2.5", "px-3", "px-4", "px-5", "px-6", "px-8",
    "py-0", "py-0.5", "py-1", "py-1.5", "py-2", "py-2.5", "py-3", "py-3.5", "py-4", "py-6", "py-8", "py-10", "py-12", "py-16",
    "pt-2", "pt-3", "pb-1", "pb-2", "pb-3", "pb-4", "pb-20", "pb-28",
    "pl-1", "pr-1",
    "m-0", "m-1", "m-2", "m-3", "m-4",
    "mx-1", "mx-4", "mx-auto", "-mx-1",
    "my-2", "my-3", "my-4",
    "mt-0.5", "mt-1", "mt-1.5", "mt-2", "mt-3", "mt-4", "mt-6", "mt-8",
    "mb-1", "mb-1.5", "mb-2", "mb-3", "mb-4", "mb-5", "mb-6", "mb-8", "mb-10",
    "ml-1", "ml-2", "ml-3", "ml-4", "ml-auto",
    "mr-1",
    "-mt-4",
    "space-y-0.5", "space-y-1", "space-y-1.5", "space-y-2", "space-y-3", "space-y-4", "space-y-5", "space-y-6",
    // Sizing
    "h-1.5", "h-2", "h-3", "h-4", "h-5", "h-6", "h-7", "h-8", "h-9", "h-10", "h-12", "h-14", "h-16", "h-20", "h-24", "h-28", "h-32",
    "h-full", "h-auto",
    "w-2", "w-3", "w-4", "w-5", "w-6", "w-8", "w-9", "w-10", "w-12", "w-14", "w-16", "w-20", "w-24", "w-32", "w-36", "w-40", "w-48",
    "w-auto", "w-full", "w-0.5",
    "min-w-0", "max-w-0",
    "max-w-sm", "max-w-md", "max-w-lg", "max-w-xl", "max-w-2xl", "max-w-3xl", "max-w-4xl", "max-w-5xl", "max-w-7xl", "max-w-full",
    "min-h-screen",
    "max-h-24", "max-h-48", "max-h-64",
    "flex-1", "flex-shrink-0", "shrink-0",
    // Display
    "block", "inline-block", "inline", "flex", "inline-flex", "table", "grid", "hidden",
    // Flex
    "flex-col", "flex-row", "flex-wrap", "flex-nowrap",
    "items-start", "items-end", "items-center", "items-stretch",
    "justify-end", "justify-center", "justify-between", "justify-around",
    "self-start", "self-end", "self-center", "self-stretch",
    // Grid
    "grid-cols-1", "grid-cols-2", "grid-cols-3", "grid-cols-4", "grid-cols-5", "grid-cols-6", "grid-cols-7", "grid-cols-12",
    "col-span-full",
    // Position
    "fixed", "absolute", "relative", "sticky",
    "inset-0",
    "top-0", "top-2", "top-20",
    "bottom-0", "bottom-24",
    "left-0", "left-2",
    "right-0", "right-4", "right-80",
    "z-50", "z-\[100\]", "z-\[9999\]", "z-\[99999\]",
    // Text
    "text-xs", "text-sm", "text-base", "text-lg", "text-xl", "text-2xl", "text-3xl", "text-4xl", "text-5xl", "text-6xl",
    "text-left", "text-center", "text-right",
    "font-normal", "font-medium", "font-semibold", "font-bold",
    "uppercase", "capitalize", "italic",
    "truncate", "whitespace-nowrap", "break-all",
    "leading-tight", "leading-relaxed",
    "tracking-wider", "tracking-widest",
    "font-sans", "font-mono",
    "antialiased",
    // Text colors
    "text-white", "text-black",
    "text-slate-50", "text-slate-100", "text-slate-200", "text-slate-300", "text-slate-400", "text-slate-500", "text-slate-600", "text-slate-700", "text-slate-800", "text-slate-900",
    "text-blue-50", "text-blue-100", "text-blue-200", "text-blue-300", "text-blue-400", "text-blue-500", "text-blue-600", "text-blue-700", "text-blue-800",
    "text-red-50", "text-red-100", "text-red-300", "text-red-400", "text-red-500", "text-red-600", "text-red-700", "text-red-800",
    "text-green-50", "text-green-100", "text-green-300", "text-green-400", "text-green-600", "text-green-700", "text-green-800",
    "text-amber-50", "text-amber-100", "text-amber-300", "text-amber-400", "text-amber-600", "text-amber-700", "text-amber-800",
    "text-emerald-50", "text-emerald-300", "text-emerald-400", "text-emerald-500", "text-emerald-600",
    "text-rose-200", "text-rose-300", "text-rose-400", "text-rose-600",
    "text-indigo-600",
    "text-purple-400", "text-purple-600",
    "text-violet-600",
    "text-cyan-400",
    "text-teal-400",
    "text-white/80", "text-white/70", "text-white/60", "text-white/50", "text-white/40", "text-white/30", "text-white/20",
    "text-blue-100/80", "text-blue-200/70",
    "text-rose-300/80",
    // Background colors
    "bg-white", "bg-black/60",
    "bg-slate-50", "bg-slate-50/50", "bg-slate-100", "bg-slate-200", "bg-slate-300", "bg-slate-400", "bg-slate-600", "bg-slate-700", "bg-slate-800", "bg-slate-800/50", "bg-slate-900", "bg-slate-900/50",
    "bg-blue-50", "bg-blue-100", "bg-blue-400", "bg-blue-500", "bg-blue-600",
    "bg-red-50", "bg-red-100", "bg-red-400", "bg-red-500", "bg-red-900/20", "bg-red-900/50",
    "bg-green-50", "bg-green-100", "bg-green-400", "bg-green-500", "bg-green-600", "bg-green-900/50",
    "bg-amber-50", "bg-amber-100", "bg-amber-400", "bg-amber-500", "bg-amber-500/10",
    "bg-emerald-50", "bg-emerald-400", "bg-emerald-500", "bg-emerald-600",
    "bg-rose-50", "bg-rose-400",
    "bg-indigo-50", "bg-indigo-500/85",
    "bg-purple-50", "bg-purple-500", "bg-purple-600",
    "bg-violet-50", "bg-violet-400",
    "bg-cyan-400", "bg-cyan-600",
    "bg-teal-400", "bg-teal-500",
    "bg-yellow-500",
    "bg-white/5", "bg-white/10", "bg-white/20",
    // Gradients
    "bg-gradient-to-r", "bg-gradient-to-br",
    "from-blue-50", "from-blue-500", "from-blue-600",
    "from-amber-500",
    "from-emerald-500",
    "from-slate-500", "from-slate-900",
    "to-amber-700", "to-blue-700", "to-emerald-700",
    "to-indigo-50", "to-indigo-700",
    "to-slate-700", "to-slate-900",
    "via-slate-800",
    // Border
    "border", "border-0", "border-2", "border-4",
    "border-t", "border-b",
    "border-dashed",
    "border-t-transparent",
    "border-slate-100", "border-slate-200", "border-slate-300", "border-slate-600", "border-slate-700", "border-slate-800",
    "border-blue-100", "border-blue-200", "border-blue-400/50", "border-blue-500", "border-blue-600",
    "border-amber-200", "border-amber-500/20",
    "border-emerald-200",
    "border-green-200", "border-green-700",
    "border-red-200", "border-red-700", "border-red-800/30",
    "border-rose-200", "border-rose-500/20",
    "border-indigo-200",
    "border-violet-200",
    "border-white/10", "border-white/20",
    // Rounded
    "rounded", "rounded-md", "rounded-lg", "rounded-xl", "rounded-2xl", "rounded-full",
    "rounded-t",
    // Overflow
    "overflow-hidden", "overflow-x-auto", "overflow-y-auto",
    // Shadows
    "shadow-sm", "shadow-lg",
    // Opacity
    "opacity-50", "opacity-60", "opacity-80", "opacity-100",
    // Transitions
    "transition", "transition-all", "transition-colors", "transition-shadow",
    // Cursor
    "cursor-pointer", "cursor-not-allowed", "cursor-move",
    // Transform
    "transform", "-rotate-90",
    "animate-spin",
    // Effects
    "filter", "backdrop-blur-xl",
    "outline-none",
    // Placeholder
    "placeholder-white/30", "placeholder-white/40",
    // Accent
    "accent-blue-500",
    // Object
    "object-contain",
    // Divide
    "divide-y", "divide-slate-100",
    // Responsive sm:
    "sm:flex", "sm:hidden", "sm:inline",
    "sm:grid-cols-2", "sm:grid-cols-3",
    "sm:flex-row",
    "sm:items-center",
    "sm:gap-4", "sm:gap-6",
    "sm:space-y-6",
    "sm:p-6",
    "sm:px-4", "sm:px-5", "sm:px-6",
    "sm:py-12",
    "sm:pb-6",
    "sm:text-2xl",
    "sm:mb-8",
    "sm:h-8",
    "sm:max-w-none",
    "sm:max-w-[120px]", "sm:max-w-[150px]", "sm:max-w-[180px]", "sm:max-w-[200px]",
    "sm:right-80",
    "sm:flex-wrap",
    // Responsive md:
    "md:inline",
    "md:grid-cols-2", "md:grid-cols-3", "md:grid-cols-4",
    "md:p-7",
    "md:text-xl",
    // Responsive lg:
    "lg:col-span-2",
    "lg:grid-cols-2", "lg:grid-cols-3", "lg:grid-cols-4", "lg:grid-cols-6",
    "lg:px-8",
    "lg:w-56",
    // Responsive xl:
    "xl:grid-cols-4",
    // Hover states
    "hover:bg-slate-50", "hover:bg-slate-50/50", "hover:bg-slate-100", "hover:bg-slate-200", "hover:bg-slate-600", "hover:bg-slate-700",
    "hover:bg-blue-500", "hover:bg-blue-700",
    "hover:bg-green-100", "hover:bg-green-500",
    "hover:bg-emerald-100", "hover:bg-emerald-500", "hover:bg-emerald-700",
    "hover:bg-amber-100",
    "hover:bg-red-100",
    "hover:bg-indigo-500",
    "hover:bg-purple-700",
    "hover:bg-cyan-500",
    "hover:bg-white/10", "hover:bg-white/20",
    "hover:bg-[rgba(51,65,85,0.3)]",
    "hover:text-slate-300", "hover:text-slate-600", "hover:text-slate-700", "hover:text-slate-800",
    "hover:text-blue-100", "hover:text-blue-300", "hover:text-blue-600", "hover:text-blue-800",
    "hover:text-red-500", "hover:text-red-600", "hover:text-red-700",
    "hover:text-white",
    "hover:underline",
    "hover:shadow-sm", "hover:shadow-md",
    "hover:border-blue-400", "hover:border-blue-400/50", "hover:border-blue-500/50",
    "hover:border-cyan-600/50", "hover:border-rose-500/40",
    // Focus states
    "focus:outline-none",
    "focus:ring-2",
    "focus:ring-blue-500", "focus:ring-blue-500/20",
    "focus:border-blue-400", "focus:border-blue-500", "focus:border-white/30",
    "focus:not-sr-only", "focus:absolute", "focus:left-2", "focus:top-2",
    "focus:z-[99999]", "focus:rounded-lg",
    "focus:px-4", "focus:py-2",
    "focus:text-sm", "focus:font-medium",
    "focus:text-white", "focus:bg-blue-600",
    // Disabled
    "disabled:opacity-30", "disabled:opacity-50",
    // Peer
    "peer-checked:bg-blue-600",
    "peer-checked:after:translate-x-full",
    "peer-focus:outline-none",
    // After
    "after:absolute", "after:left-[2px]", "after:top-0.5",
    "after:h-4", "after:w-4",
    "after:rounded-full", "after:border",
    "after:border-slate-300", "after:bg-white",
    "after:transition-all",
    "after:content-['']",
    // Custom values used in templates
    "text-[0.6rem]", "text-[#475569]", "text-[#64748b]",
    "bg-[#1e293b]", "bg-[#334155]",
    "border-[#334155]", "border-[#475569]",
    "min-w-[130px]", "min-w-[70px]", "min-w-[40px]", "min-w-[3ch]",
    "max-w-[120px]", "max-w-[140px]", "max-w-[200px]", "max-w-[80%]",
    "h-28", "w-40",
    "z-[9999]", "z-[100]", "z-[99999]",
    "-mt-4",
    "right-80",
    // Grid responsive combos
    "sm:grid-cols-2", "sm:grid-cols-3",
    "md:grid-cols-2", "md:grid-cols-3", "md:grid-cols-4",
    "lg:grid-cols-2", "lg:grid-cols-3", "lg:grid-cols-4", "lg:grid-cols-6",
    "xl:grid-cols-4",
    // Display responsive
    "sm:flex", "sm:hidden", "sm:inline",
    "md:inline",
    // Flex responsive
    "sm:flex-row",
    "sm:items-center",
    // Spacing responsive
    "sm:gap-4", "sm:gap-6",
    "sm:space-y-6",
    "sm:p-6",
    "sm:px-4", "sm:px-5", "sm:px-6",
    "sm:py-12",
    "sm:pb-6",
    // Text responsive
    "sm:text-2xl",
    "md:text-xl",
    "sm:text-[0.65rem]",
    // Sizing responsive
    "sm:h-8",
    "sm:max-w-none",
    "sm:max-w-[120px]", "sm:max-w-[150px]", "sm:max-w-[180px]", "sm:max-w-[200px]",
    "sm:right-80",
    "lg:w-56", "lg:px-8",
    // Margin responsive
    "sm:mb-8",
    // Grid responsive
    "lg:col-span-2",
    // Border
    "border-slate-100", "border-slate-200", "border-slate-300",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
}
