"""SHUNYA — Collaboration & Multi-user Operating System (Milestone IX)

Transforms SHUNYA from an individual workspace into an organizational
operating system. Multiple humans work simultaneously inside the same
business reality. Every participant sees the same canonical objects,
evidence, reasoning, and executive priorities while receiving a
role-appropriate view.

Architecture:
  PresenceRuntime       → Who is viewing/editing what (continuous)
  WorkspaceSession      → Temporary UI state (never business truth)
  RoleAwareWorkspace    → Runtime-filtered visibility per role
  SharedConversation    → Organizational memory with object links
  DecisionCollaboration → Discussion, approvals, objections, resolution
  AssignmentIntelligence → RACI-like: responsible, supporting, approver, observer, sponsor, escalation
  ActivityTimeline      → Immutable event log per object
  LiveCollaboration     → Runtime events: presence, focus, updates
  ConflictResolution    → Deterministic merge for concurrent access
  OrganizationalMemory  → Searchable, traceable, replayable
  ExecutiveOversight    → Generated by Executive Intelligence
"""

from app.collaboration.models import (
    PresenceEntry, WorkspaceSession, RoleDefinition,
    ConversationMessage, DecisionDiscussion, DecisionVote,
    Assignment, AssignmentRole,
    ActivityEvent, CollaborationEvent,
    ConflictRecord, CollaborationStats,
    CollaborationConfig, CollaborationFilter,
)
from app.collaboration.engine import (
    CollaborationRuntime,
    PresenceRuntime, SessionManager,
    RoleAwareWorkspace, SharedConversation,
    DecisionCollaboration, AssignmentIntelligence,
    ActivityTimeline, LiveCollaboration,
    ConflictResolver, OrganizationalMemory,
    ExecutiveOversight,
    get_collaboration_runtime, reset_collaboration_runtime,
)

__all__ = [
    "CollaborationRuntime",
    "PresenceRuntime", "SessionManager",
    "RoleAwareWorkspace", "SharedConversation",
    "DecisionCollaboration", "AssignmentIntelligence",
    "ActivityTimeline", "LiveCollaboration",
    "ConflictResolver", "OrganizationalMemory",
    "ExecutiveOversight",
    "get_collaboration_runtime", "reset_collaboration_runtime",
    "PresenceEntry", "WorkspaceSession", "RoleDefinition",
    "ConversationMessage", "DecisionDiscussion", "DecisionVote",
    "Assignment", "AssignmentRole",
    "ActivityEvent", "CollaborationEvent",
    "ConflictRecord", "CollaborationStats",
    "CollaborationConfig", "CollaborationFilter",
]