"""Shunya OS — Vertical Template Registry.

Pre-built entity type packs for different business verticals.
When a new business signs up, its vertical template defines:
- Which entity types are created
- Their labels, icons, statuses, and layouts
- Code prefix guidelines
- Dashboard metrics & quick actions
- Default AI configuration
"""

# Each vertical defines a set of entity type definitions to auto-create.
# The entity engine is the same — only terminology, icons, and flows change.

VERTICAL_TEMPLATES = {
    "travel": {
        "label": "Travel & Hospitality",
        "icon": "🏖️",
        "description": "Tour operators, travel agencies, hotels, destinations",
        "code_prefix": "PC",  # default prefix for first entity type
        "theme_icon": "✈️",
        "default_brand_color": "#2563eb",
        "default_brand_secondary": "#7c3aed",
        "entity_types": [
            {
                "type": "lead",
                "label": "Lead",
                "label_plural": "Leads",
                "icon": "🎯",
                "primary_field": "name",
                "layout": "kanban",
                "statuses": ["new", "contacted", "qualified", "proposal", "converted", "lost"],
                "schema": [
                    {"name": "name", "label": "Name", "type": "text", "required": True},
                    {"name": "email", "label": "Email", "type": "email"},
                    {"name": "phone", "label": "Phone", "type": "phone"},
                    {"name": "destination", "label": "Destination", "type": "text"},
                    {"name": "budget", "label": "Budget (₹)", "type": "number"},
                    {"name": "source", "label": "Source", "type": "select", "options": ["website", "referral", "walk-in", "instagram", "whatsapp", "phone"]},
                    {"name": "notes", "label": "Notes", "type": "textarea"},
                ],
            },
            {
                "type": "booking",
                "label": "Booking",
                "label_plural": "Bookings",
                "icon": "📅",
                "primary_field": "guest_name",
                "layout": "table",
                "statuses": ["enquiry", "hold", "confirmed", "in-progress", "completed", "cancelled"],
                "schema": [
                    {"name": "guest_name", "label": "Guest Name", "type": "text", "required": True},
                    {"name": "destination", "label": "Destination", "type": "text"},
                    {"name": "check_in", "label": "Check-in", "type": "date"},
                    {"name": "check_out", "label": "Check-out", "type": "date"},
                    {"name": "total_amount", "label": "Total Amount", "type": "number"},
                    {"name": "pax", "label": "Pax", "type": "number"},
                    {"name": "notes", "label": "Notes", "type": "textarea"},
                ],
            },
            {
                "type": "supplier",
                "label": "Supplier",
                "label_plural": "Suppliers",
                "icon": "🏨",
                "primary_field": "name",
                "layout": "table",
                "statuses": ["active", "inactive", "blacklisted"],
                "schema": [
                    {"name": "name", "label": "Supplier Name", "type": "text", "required": True},
                    {"name": "category", "label": "Category", "type": "select", "options": ["hotel", "transport", "guide", "activity", "insurance", "other"]},
                    {"name": "contact", "label": "Contact Person", "type": "text"},
                    {"name": "phone", "label": "Phone", "type": "phone"},
                    {"name": "email", "label": "Email", "type": "email"},
                    {"name": "city", "label": "City", "type": "text"},
                    {"name": "gstin", "label": "GSTIN", "type": "text"},
                    {"name": "payment_terms", "label": "Payment Terms", "type": "text"},
                ],
            },
            {
                "type": "invoice",
                "label": "Invoice",
                "label_plural": "Invoices",
                "icon": "🧾",
                "primary_field": "invoice_number",
                "layout": "table",
                "statuses": ["draft", "sent", "paid", "overdue", "cancelled"],
                "schema": [
                    {"name": "invoice_number", "label": "Invoice #", "type": "text", "required": True},
                    {"name": "customer", "label": "Customer", "type": "text"},
                    {"name": "total_amount", "label": "Total (₹)", "type": "number"},
                    {"name": "due_date", "label": "Due Date", "type": "date"},
                    {"name": "status", "label": "Status", "type": "select", "options": ["draft", "sent", "paid", "overdue", "cancelled"]},
                ],
            },
            {
                "type": "itinerary",
                "label": "Itinerary",
                "label_plural": "Itineraries",
                "icon": "🗺️",
                "primary_field": "title",
                "layout": "cards",
                "statuses": ["draft", "sent", "confirmed"],
                "schema": [
                    {"name": "title", "label": "Title", "type": "text", "required": True},
                    {"name": "destination", "label": "Destination", "type": "text"},
                    {"name": "duration", "label": "Duration (days)", "type": "number"},
                    {"name": "highlights", "label": "Highlights", "type": "textarea"},
                ],
            },
        ],
        "dashboard_metrics": [
            {"key": "total_bookings", "label": "Total Bookings", "icon": "📅"},
            {"key": "monthly_revenue", "label": "Monthly Revenue", "icon": "💰", "prefix": "₹"},
            {"key": "active_leads", "label": "Active Leads", "icon": "🎯"},
            {"key": "pending_invoices", "label": "Pending Invoices", "icon": "🧾"},
        ],
        "quick_actions": [
            {"label": "New Booking", "url": "/entities/booking/new", "icon": "📅"},
            {"label": "New Lead", "url": "/entities/lead/new", "icon": "🎯"},
            {"label": "New Invoice", "url": "/entities/invoice/new", "icon": "🧾"},
        ],
    },
    "healthcare": {
        "label": "Healthcare",
        "icon": "🏥",
        "description": "Hospitals, clinics, diagnostic centers, pharmacy",
        "code_prefix": "HOS",
        "theme_icon": "🏥",
        "default_brand_color": "#059669",
        "default_brand_secondary": "#0d9488",
        "entity_types": [
            {
                "type": "patient",
                "label": "Patient",
                "label_plural": "Patients",
                "icon": "👤",
                "primary_field": "name",
                "layout": "table",
                "statuses": ["active", "in-treatment", "discharged", "referred"],
                "schema": [
                    {"name": "name", "label": "Full Name", "type": "text", "required": True},
                    {"name": "age", "label": "Age", "type": "number"},
                    {"name": "gender", "label": "Gender", "type": "select", "options": ["male", "female", "other"]},
                    {"name": "phone", "label": "Phone", "type": "phone"},
                    {"name": "blood_group", "label": "Blood Group", "type": "select", "options": ["A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-"]},
                    {"name": "address", "label": "Address", "type": "textarea"},
                    {"name": "medical_history", "label": "Medical History", "type": "textarea"},
                ],
            },
            {
                "type": "admission",
                "label": "Admission",
                "label_plural": "Admissions",
                "icon": "🏨",
                "primary_field": "patient_name",
                "layout": "kanban",
                "statuses": ["scheduled", "admitted", "in-care", "discharge-ready", "discharged"],
                "schema": [
                    {"name": "patient_name", "label": "Patient Name", "type": "text", "required": True},
                    {"name": "ward", "label": "Ward", "type": "text"},
                    {"name": "doctor", "label": "Attending Doctor", "type": "text"},
                    {"name": "admission_date", "label": "Admission Date", "type": "date"},
                    {"name": "diagnosis", "label": "Diagnosis", "type": "textarea"},
                    {"name": "insurance", "label": "Insurance Provider", "type": "text"},
                ],
            },
            {
                "type": "appointment",
                "label": "Appointment",
                "label_plural": "Appointments",
                "icon": "📅",
                "primary_field": "patient_name",
                "layout": "calendar",
                "statuses": ["scheduled", "confirmed", "in-progress", "completed", "no-show", "cancelled"],
                "schema": [
                    {"name": "patient_name", "label": "Patient Name", "type": "text", "required": True},
                    {"name": "doctor", "label": "Doctor", "type": "text"},
                    {"name": "department", "label": "Department", "type": "text"},
                    {"name": "date", "label": "Date", "type": "date"},
                    {"name": "time", "label": "Time", "type": "text"},
                    {"name": "reason", "label": "Reason", "type": "textarea"},
                ],
            },
            {
                "type": "invoice",
                "label": "Bill",
                "label_plural": "Bills",
                "icon": "🧾",
                "primary_field": "bill_number",
                "layout": "table",
                "statuses": ["draft", "sent", "paid", "overdue"],
                "schema": [
                    {"name": "bill_number", "label": "Bill #", "type": "text", "required": True},
                    {"name": "patient", "label": "Patient", "type": "text"},
                    {"name": "total", "label": "Total (₹)", "type": "number"},
                    {"name": "insurance_claim", "label": "Insurance Claim", "type": "text"},
                    {"name": "due_date", "label": "Due Date", "type": "date"},
                ],
            },
        ],
        "dashboard_metrics": [
            {"key": "total_patients", "label": "Total Patients", "icon": "👤"},
            {"key": "active_admissions", "label": "Active Admissions", "icon": "🏨"},
            {"key": "today_appointments", "label": "Today's Appointments", "icon": "📅"},
            {"key": "pending_bills", "label": "Pending Bills", "icon": "🧾"},
        ],
        "quick_actions": [
            {"label": "New Patient", "url": "/entities/patient/new", "icon": "👤"},
            {"label": "New Admission", "url": "/entities/admission/new", "icon": "🏨"},
            {"label": "New Appointment", "url": "/entities/appointment/new", "icon": "📅"},
        ],
    },
    "legal": {
        "label": "Legal Services",
        "icon": "⚖️",
        "description": "Law firms, advocates, legal consultants, corporate legal",
        "code_prefix": "LAW",
        "theme_icon": "⚖️",
        "default_brand_color": "#1e293b",
        "default_brand_secondary": "#475569",
        "entity_types": [
            {
                "type": "client",
                "label": "Client",
                "label_plural": "Clients",
                "icon": "👤",
                "primary_field": "name",
                "layout": "table",
                "statuses": ["active", "inactive"],
                "schema": [
                    {"name": "name", "label": "Client Name", "type": "text", "required": True},
                    {"name": "phone", "label": "Phone", "type": "phone"},
                    {"name": "email", "label": "Email", "type": "email"},
                    {"name": "type", "label": "Type", "type": "select", "options": ["individual", "corporate", "government"]},
                    {"name": "notes", "label": "Notes", "type": "textarea"},
                ],
            },
            {
                "type": "case",
                "label": "Case",
                "label_plural": "Cases",
                "icon": "📁",
                "primary_field": "title",
                "layout": "kanban",
                "statuses": ["filing", "hearing", "adjourned", "arguments", "judgment", "appeal", "closed"],
                "schema": [
                    {"name": "title", "label": "Case Title", "type": "text", "required": True},
                    {"name": "client", "label": "Client", "type": "text"},
                    {"name": "court", "label": "Court", "type": "text"},
                    {"name": "case_type", "label": "Case Type", "type": "select", "options": ["civil", "criminal", "corporate", "family", "tax", "constitutional"]},
                    {"name": "filing_date", "label": "Filing Date", "type": "date"},
                    {"name": "opposing_party", "label": "Opposing Party", "type": "text"},
                    {"name": "description", "label": "Description", "type": "textarea"},
                ],
            },
            {
                "type": "hearing",
                "label": "Hearing",
                "label_plural": "Hearings",
                "icon": "🏛️",
                "primary_field": "case_title",
                "layout": "calendar",
                "statuses": ["scheduled", "completed", "adjourned"],
                "schema": [
                    {"name": "case_title", "label": "Case", "type": "text", "required": True},
                    {"name": "court", "label": "Court", "type": "text"},
                    {"name": "date", "label": "Date", "type": "date"},
                    {"name": "judge", "label": "Judge", "type": "text"},
                    {"name": "notes", "label": "Notes", "type": "textarea"},
                ],
            },
            {
                "type": "invoice",
                "label": "Invoice",
                "label_plural": "Invoices",
                "icon": "🧾",
                "primary_field": "invoice_number",
                "layout": "table",
                "statuses": ["draft", "sent", "paid", "overdue"],
                "schema": [
                    {"name": "invoice_number", "label": "Invoice #", "type": "text", "required": True},
                    {"name": "client", "label": "Client", "type": "text"},
                    {"name": "case", "label": "Case", "type": "text"},
                    {"name": "amount", "label": "Amount (₹)", "type": "number"},
                    {"name": "hours_billed", "label": "Hours Billed", "type": "number"},
                    {"name": "due_date", "label": "Due Date", "type": "date"},
                ],
            },
        ],
        "dashboard_metrics": [
            {"key": "active_cases", "label": "Active Cases", "icon": "📁"},
            {"key": "clients", "label": "Clients", "icon": "👤"},
            {"key": "upcoming_hearings", "label": "Upcoming Hearings", "icon": "🏛️"},
            {"key": "outstanding", "label": "Outstanding (₹)", "icon": "💰", "prefix": "₹"},
        ],
        "quick_actions": [
            {"label": "New Case", "url": "/entities/case/new", "icon": "📁"},
            {"label": "New Client", "url": "/entities/client/new", "icon": "👤"},
            {"label": "New Invoice", "url": "/entities/invoice/new", "icon": "🧾"},
        ],
    },
    "government": {
        "label": "Government & Public",
        "icon": "🏛️",
        "description": "State departments, municipalities, public services",
        "code_prefix": "GOV",
        "theme_icon": "🏛️",
        "default_brand_color": "#1d4ed8",
        "default_brand_secondary": "#1e40af",
        "entity_types": [
            {
                "type": "citizen",
                "label": "Citizen",
                "label_plural": "Citizens",
                "icon": "👥",
                "primary_field": "name",
                "layout": "table",
                "statuses": ["active", "inactive"],
                "schema": [
                    {"name": "name", "label": "Full Name", "type": "text", "required": True},
                    {"name": "aadhaar", "label": "Aadhaar/Voter ID", "type": "text"},
                    {"name": "phone", "label": "Phone", "type": "phone"},
                    {"name": "address", "label": "Address", "type": "textarea"},
                    {"name": "ward", "label": "Ward/Constituency", "type": "text"},
                ],
            },
            {
                "type": "application",
                "label": "Application",
                "label_plural": "Applications",
                "icon": "📋",
                "primary_field": "applicant_name",
                "layout": "kanban",
                "statuses": ["received", "under-review", "approved", "rejected", "disbursed"],
                "schema": [
                    {"name": "applicant_name", "label": "Applicant", "type": "text", "required": True},
                    {"name": "scheme", "label": "Scheme Name", "type": "text"},
                    {"name": "amount", "label": "Amount (₹)", "type": "number"},
                    {"name": "submitted", "label": "Submitted Date", "type": "date"},
                    {"name": "notes", "label": "Notes", "type": "textarea"},
                ],
            },
            {
                "type": "scheme",
                "label": "Scheme",
                "label_plural": "Schemes",
                "icon": "📜",
                "primary_field": "name",
                "layout": "table",
                "statuses": ["active", "closed"],
                "schema": [
                    {"name": "name", "label": "Scheme Name", "type": "text", "required": True},
                    {"name": "department", "label": "Department", "type": "text"},
                    {"name": "budget", "label": "Budget (₹)", "type": "number"},
                    {"name": "start_date", "label": "Start Date", "type": "date"},
                    {"name": "end_date", "label": "End Date", "type": "date"},
                    {"name": "description", "label": "Description", "type": "textarea"},
                ],
            },
            {
                "type": "complaint",
                "label": "Complaint",
                "label_plural": "Complaints",
                "icon": "📢",
                "primary_field": "citizen_name",
                "layout": "kanban",
                "statuses": ["received", "investigating", "resolved", "closed"],
                "schema": [
                    {"name": "citizen_name", "label": "Citizen", "type": "text", "required": True},
                    {"name": "department", "label": "Department", "type": "text"},
                    {"name": "description", "label": "Description", "type": "textarea", "required": True},
                    {"name": "priority", "label": "Priority", "type": "select", "options": ["low", "medium", "high", "urgent"]},
                    {"name": "resolution", "label": "Resolution", "type": "textarea"},
                ],
            },
        ],
        "dashboard_metrics": [
            {"key": "total_applications", "label": "Applications", "icon": "📋"},
            {"key": "pending", "label": "Pending Review", "icon": "⏳"},
            {"key": "resolved_complaints", "label": "Resolved Complaints", "icon": "✅"},
            {"key": "active_schemes", "label": "Active Schemes", "icon": "📜"},
        ],
        "quick_actions": [
            {"label": "New Application", "url": "/entities/application/new", "icon": "📋"},
            {"label": "New Complaint", "url": "/entities/complaint/new", "icon": "📢"},
            {"label": "New Citizen", "url": "/entities/citizen/new", "icon": "👥"},
        ],
    },
    "transport": {
        "label": "Transport & Logistics",
        "icon": "🚗",
        "description": "Rickshaw operators, cab services, logistics, fleet management",
        "code_prefix": "TR",
        "theme_icon": "🚗",
        "default_brand_color": "#d97706",
        "default_brand_secondary": "#ea580c",
        "entity_types": [
            {
                "type": "driver",
                "label": "Driver",
                "label_plural": "Drivers",
                "icon": "👤",
                "primary_field": "name",
                "layout": "table",
                "statuses": ["active", "on-leave", "inactive"],
                "schema": [
                    {"name": "name", "label": "Driver Name", "type": "text", "required": True},
                    {"name": "phone", "label": "Phone", "type": "phone"},
                    {"name": "license", "label": "License #", "type": "text"},
                    {"name": "vehicle", "label": "Assigned Vehicle", "type": "text"},
                    {"name": "earnings", "label": "Total Earnings (₹)", "type": "number"},
                ],
            },
            {
                "type": "vehicle",
                "label": "Vehicle",
                "label_plural": "Vehicles",
                "icon": "🚙",
                "primary_field": "registration",
                "layout": "table",
                "statuses": ["active", "maintenance", "retired"],
                "schema": [
                    {"name": "registration", "label": "Registration #", "type": "text", "required": True},
                    {"name": "model", "label": "Model", "type": "text"},
                    {"name": "type", "label": "Type", "type": "select", "options": ["rickshaw", "cab", "auto", "tempo", "truck", "bus"]},
                    {"name": "owner", "label": "Owner", "type": "text"},
                    {"name": "fitness_expiry", "label": "Fitness Expiry", "type": "date"},
                ],
            },
            {
                "type": "trip",
                "label": "Trip",
                "label_plural": "Trips",
                "icon": "📋",
                "primary_field": "customer",
                "layout": "table",
                "statuses": ["requested", "assigned", "in-progress", "completed", "cancelled"],
                "schema": [
                    {"name": "customer", "label": "Customer", "type": "text", "required": True},
                    {"name": "from_location", "label": "From", "type": "text"},
                    {"name": "to_location", "label": "To", "type": "text"},
                    {"name": "driver", "label": "Driver", "type": "text"},
                    {"name": "fare", "label": "Fare (₹)", "type": "number"},
                    {"name": "distance", "label": "Distance (km)", "type": "number"},
                ],
            },
            {
                "type": "expense",
                "label": "Expense",
                "label_plural": "Expenses",
                "icon": "💸",
                "primary_field": "description",
                "layout": "table",
                "statuses": ["pending", "approved", "rejected"],
                "schema": [
                    {"name": "description", "label": "Description", "type": "text", "required": True},
                    {"name": "category", "label": "Category", "type": "select", "options": ["fuel", "maintenance", "toll", "food", "other"]},
                    {"name": "amount", "label": "Amount (₹)", "type": "number"},
                    {"name": "date", "label": "Date", "type": "date"},
                    {"name": "vehicle", "label": "Vehicle", "type": "text"},
                ],
            },
        ],
        "dashboard_metrics": [
            {"key": "total_trips", "label": "Total Trips", "icon": "📋"},
            {"key": "active_drivers", "label": "Active Drivers", "icon": "👤"},
            {"key": "today_earnings", "label": "Today's Earnings", "icon": "💰", "prefix": "₹"},
            {"key": "fleet_size", "label": "Fleet Size", "icon": "🚙"},
        ],
        "quick_actions": [
            {"label": "New Trip", "url": "/entities/trip/new", "icon": "📋"},
            {"label": "New Driver", "url": "/entities/driver/new", "icon": "👤"},
            {"label": "New Expense", "url": "/entities/expense/new", "icon": "💸"},
        ],
    },
    "retail": {
        "label": "Retail & E-commerce",
        "icon": "🛍️",
        "description": "Shops, e-commerce, wholesalers, distributors",
        "code_prefix": "RT",
        "theme_icon": "🛍️",
        "default_brand_color": "#dc2626",
        "default_brand_secondary": "#b91c1c",
        "entity_types": [
            {
                "type": "product",
                "label": "Product",
                "label_plural": "Products",
                "icon": "📦",
                "primary_field": "name",
                "layout": "cards",
                "statuses": ["in-stock", "low-stock", "out-of-stock", "discontinued"],
                "schema": [
                    {"name": "name", "label": "Product Name", "type": "text", "required": True},
                    {"name": "sku", "label": "SKU", "type": "text"},
                    {"name": "price", "label": "Price (₹)", "type": "number"},
                    {"name": "stock", "label": "Stock Quantity", "type": "number"},
                    {"name": "category", "label": "Category", "type": "text"},
                    {"name": "supplier", "label": "Supplier", "type": "text"},
                ],
            },
            {
                "type": "order",
                "label": "Order",
                "label_plural": "Orders",
                "icon": "🛒",
                "primary_field": "customer",
                "layout": "kanban",
                "statuses": ["pending", "confirmed", "processing", "shipped", "delivered", "cancelled"],
                "schema": [
                    {"name": "customer", "label": "Customer", "type": "text", "required": True},
                    {"name": "products", "label": "Products", "type": "textarea"},
                    {"name": "total", "label": "Total (₹)", "type": "number"},
                    {"name": "order_date", "label": "Order Date", "type": "date"},
                    {"name": "delivery_address", "label": "Delivery Address", "type": "textarea"},
                ],
            },
            {
                "type": "customer",
                "label": "Customer",
                "label_plural": "Customers",
                "icon": "👤",
                "primary_field": "name",
                "layout": "table",
                "statuses": ["active", "inactive"],
                "schema": [
                    {"name": "name", "label": "Name", "type": "text", "required": True},
                    {"name": "phone", "label": "Phone", "type": "phone"},
                    {"name": "email", "label": "Email", "type": "email"},
                    {"name": "total_purchases", "label": "Total Purchases (₹)", "type": "number"},
                    {"name": "notes", "label": "Notes", "type": "textarea"},
                ],
            },
        ],
        "dashboard_metrics": [
            {"key": "total_orders", "label": "Orders", "icon": "🛒"},
            {"key": "products", "label": "Products", "icon": "📦"},
            {"key": "revenue", "label": "Revenue (₹)", "icon": "💰", "prefix": "₹"},
            {"key": "low_stock", "label": "Low Stock Items", "icon": "⚠️"},
        ],
        "quick_actions": [
            {"label": "New Order", "url": "/entities/order/new", "icon": "🛒"},
            {"label": "Add Product", "url": "/entities/product/new", "icon": "📦"},
            {"label": "New Customer", "url": "/entities/customer/new", "icon": "👤"},
        ],
    },
    "education": {
        "label": "Education & Training",
        "icon": "🎓",
        "description": "Schools, coaching centers, universities, online courses",
        "code_prefix": "EDU",
        "theme_icon": "🎓",
        "default_brand_color": "#7c3aed",
        "default_brand_secondary": "#6d28d9",
        "entity_types": [
            {
                "type": "student",
                "label": "Student",
                "label_plural": "Students",
                "icon": "👨‍🎓",
                "primary_field": "name",
                "layout": "table",
                "statuses": ["active", "graduated", "withdrawn"],
                "schema": [
                    {"name": "name", "label": "Student Name", "type": "text", "required": True},
                    {"name": "phone", "label": "Phone", "type": "phone"},
                    {"name": "course", "label": "Course", "type": "text"},
                    {"name": "batch", "label": "Batch", "type": "text"},
                    {"name": "fees", "label": "Fees (₹)", "type": "number"},
                    {"name": "address", "label": "Address", "type": "textarea"},
                ],
            },
            {
                "type": "course",
                "label": "Course",
                "label_plural": "Courses",
                "icon": "📚",
                "primary_field": "name",
                "layout": "cards",
                "statuses": ["active", "completed", "cancelled"],
                "schema": [
                    {"name": "name", "label": "Course Name", "type": "text", "required": True},
                    {"name": "duration", "label": "Duration (months)", "type": "number"},
                    {"name": "fee", "label": "Fee (₹)", "type": "number"},
                    {"name": "instructor", "label": "Instructor", "type": "text"},
                    {"name": "max_students", "label": "Max Students", "type": "number"},
                ],
            },
            {
                "type": "attendance",
                "label": "Attendance",
                "label_plural": "Attendance",
                "icon": "✅",
                "primary_field": "student_name",
                "layout": "table",
                "statuses": ["present", "absent", "late", "leave"],
                "schema": [
                    {"name": "student_name", "label": "Student", "type": "text", "required": True},
                    {"name": "date", "label": "Date", "type": "date"},
                    {"name": "status", "label": "Status", "type": "select", "options": ["present", "absent", "late", "leave"]},
                ],
            },
            {
                "type": "fee",
                "label": "Fee Record",
                "label_plural": "Fee Records",
                "icon": "💰",
                "primary_field": "student_name",
                "layout": "table",
                "statuses": ["paid", "partial", "pending", "overdue"],
                "schema": [
                    {"name": "student_name", "label": "Student", "type": "text", "required": True},
                    {"name": "amount", "label": "Amount (₹)", "type": "number"},
                    {"name": "due_date", "label": "Due Date", "type": "date"},
                    {"name": "paid_date", "label": "Paid Date", "type": "date"},
                    {"name": "mode", "label": "Payment Mode", "type": "select", "options": ["cash", "card", "online", "cheque"]},
                ],
            },
        ],
        "dashboard_metrics": [
            {"key": "total_students", "label": "Students", "icon": "👨‍🎓"},
            {"key": "active_courses", "label": "Courses", "icon": "📚"},
            {"key": "attendance_rate", "label": "Attendance Rate", "icon": "✅", "suffix": "%"},
            {"key": "fees_collected", "label": "Fees Collected", "icon": "💰", "prefix": "₹"},
        ],
        "quick_actions": [
            {"label": "New Student", "url": "/entities/student/new", "icon": "👨‍🎓"},
            {"label": "New Course", "url": "/entities/course/new", "icon": "📚"},
            {"label": "Mark Attendance", "url": "/entities/attendance/new", "icon": "✅"},
        ],
    },
    "custom": {
        "label": "Custom Business",
        "icon": "🧩",
        "description": "Any other business — define your own entity types",
        "code_prefix": "BIZ",
        "theme_icon": "🧩",
        "default_brand_color": "#6366f1",
        "default_brand_secondary": "#4f46e5",
        "entity_types": [],  # User creates via Module Builder
        "dashboard_metrics": [
            {"key": "total_entities", "label": "Total Records", "icon": "📋"},
            {"key": "active_entities", "label": "Active This Month", "icon": "📊"},
        ],
        "quick_actions": [
            {"label": "Build Your Module", "url": "/modules", "icon": "🧩"},
            {"label": "Import Data", "url": "/ingestion", "icon": "📥"},
        ],
    },
}


def get_vertical(vertical_id: str) -> dict:
    """Get a vertical template by ID."""
    return VERTICAL_TEMPLATES.get(vertical_id)


def get_vertical_list() -> list[dict]:
    """Get simplified list for onboarding UI."""
    return [
        {"id": k, "label": v["label"], "icon": v["icon"], "description": v["description"]}
        for k, v in VERTICAL_TEMPLATES.items()
    ]


def get_entity_types_for_vertical(vertical_id: str) -> list[dict]:
    """Get the entity type definitions for a vertical."""
    v = get_vertical(vertical_id)
    if not v:
        return []
    return v.get("entity_types", [])


def get_dashboard_config(vertical_id: str) -> dict:
    """Get dashboard metrics and quick actions for a vertical."""
    v = get_vertical(vertical_id)
    if not v:
        return {"metrics": [], "quick_actions": []}
    return {
        "metrics": v.get("dashboard_metrics", []),
        "quick_actions": v.get("quick_actions", []),
    }
