"""SHUNYA Perception Engine — Data Models.

Defines the core data structures for the Perception Engine: engine input/output
contracts, input classification, observation envelopes, priority levels, and
escalation results.

All models follow the canonical contracts defined in:
    - docs/canon/INTELLIGENCE_RUNTIME_CANON.md §3 (Engine Contract)
    - docs/canon/INTELLIGENCE_RUNTIME_CANON.md §5 (Perception Engine)
    - docs/canon/07_ai_canon.md §5 (Observer Engine)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any

# ── Timestamp helper ───────────────────────────────────────────────────────────


def _now_iso() -> str:
    """Return the current UTC timestamp as ISO-8601 with 'Z' suffix."""
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


# ── Priority ───────────────────────────────────────────────────────────────────


class PerceptionPriority(str, Enum):
    """Priority levels for perception inputs.

    Determines the order in which observations are processed and delivered
    to downstream engines. Higher-priority inputs are processed first.
    """

    CRITICAL = "critical"
    """Events requiring immediate attention (system failures, security alerts)."""

    HIGH = "high"
    """Important events that should be processed promptly."""

    NORMAL = "normal"
    """Default priority for most observations."""

    LOW = "low"
    """Background signals with no urgency."""


# ── Input Types ────────────────────────────────────────────────────────────────


class InputType(str, Enum):
    """Canonical input types recognised by the Perception Engine.

    Each input that enters the system is classified into one of these types
    during the classification pipeline step.
    """

    # ── Human-generated ────────────────────────────────────────────────────
    USER_MESSAGE = "user_message"
    """A direct message from a human user."""

    USER_COMMAND = "user_command"
    """A structured command or instruction from a human."""

    USER_QUERY = "user_query"
    """A question or information request from a human."""

    # ── System-generated ────────────────────────────────────────────────────
    SYSTEM_EVENT = "system_event"
    """An event emitted by a system component."""

    SYSTEM_STATE_CHANGE = "system_state_change"
    """A detected change in system state."""

    SYSTEM_ALERT = "system_alert"
    """An alert or warning generated by a monitoring subsystem."""

    # ── External ────────────────────────────────────────────────────────────
    EXTERNAL_CALLBACK = "external_callback"
    """A callback or webhook from an external system."""

    EXTERNAL_DATA_INGEST = "external_data_ingest"
    """Bulk data ingestion from an external source."""

    # ── Derived ─────────────────────────────────────────────────────────────
    SENSOR_READING = "sensor_reading"
    """A reading from a sensor or measurement device."""

    TIMER_TRIGGER = "timer_trigger"
    """A scheduled timer or cron-triggered event."""

    INTERNAL_MESSAGE = "internal_message"
    """A message from one intelligence engine to another."""

    # ── Catch-all ───────────────────────────────────────────────────────────
    UNKNOWN = "unknown"
    """Input that could not be classified into a known type."""

    @classmethod
    def from_string(cls, value: str) -> InputType:
        """Convert a string to an InputType, falling back to UNKNOWN.

        Args:
            value: The string representation of the input type.

        Returns:
            The matching InputType, or UNKNOWN if no match.
        """
        try:
            return cls(value)
        except ValueError:
            return cls.UNKNOWN


# ── Observation Status ─────────────────────────────────────────────────────────


class ObservationStatus(str, Enum):
    """Lifecycle status of an observation.

    Observations flow from capture through processing to archival.
    """

    CAPTURED = "captured"
    """Observation has been captured but not yet validated."""

    VALIDATED = "validated"
    """Observation has passed schema validation."""

    ENRICHED = "enriched"
    """Source metadata and context have been attached."""

    CLASSIFIED = "classified"
    """Input type has been determined."""

    PRIORITY_ASSIGNED = "priority_assigned"
    """Priority level has been assigned."""

    ROUTED = "routed"
    """Observation has been routed to downstream engines."""

    ARCHIVED = "archived"
    """Observation has been archived after processing."""

    FAILED = "failed"
    """Observation processing failed at some stage."""


# ── Input Enrichment ───────────────────────────────────────────────────────────


@dataclass
class SourceMetadata:
    """Metadata about the source of a perception input.

    Captured during the enrichment phase to provide provenance and
    reliability context for confidence computation.

    Attributes:
        source_engine: Name of the engine or component that produced the input.
        source_type: Categorisation of the source (e.g., 'human', 'system').
        source_reliability: Reliability score of the source [0, 1].
        captured_at: ISO-8601 timestamp of when the input was captured.
        received_at: ISO-8601 timestamp of when the input was received.
    """

    source_engine: str = ""
    """Name of the engine or component that produced the input."""

    source_type: str = ""
    """Categorisation of the source (e.g., 'human', 'system', 'external')."""

    source_reliability: float = 0.5
    """Reliability score of the source on [0, 1]. Default 0.5 (unknown)."""

    captured_at: str = ""
    """ISO-8601 timestamp of when the input was first captured."""

    received_at: str = field(default_factory=_now_iso)
    """ISO-8601 timestamp of when the input was received by the engine."""


# ── Engine Input ───────────────────────────────────────────────────────────────


@dataclass
class EngineInput:
    """Canonical input contract for all Intelligence Engines.

    Every engine in the Intelligence Runtime consumes this shape, regardless of
    engine type. The perception engine creates EngineInput objects from raw
    signals; downstream engines receive them as their primary input.

    Attributes:
        input_type: Canonical type string (e.g., 'observation', 'query').
        payload: Structured input data as a key-value mapping.
        context: Optional pre-assembled context dict, if available.
        trace_id: Correlation ID for tracing through the engine pipeline.
        confidence_threshold: Minimum confidence before escalation is triggered.
    """

    input_type: str = ""
    """Canonical type string (e.g., 'observation', 'query', 'action_result')."""

    payload: dict[str, Any] = field(default_factory=dict)
    """Structured input data as a key-value mapping."""

    context: dict[str, Any] | None = None
    """Optional pre-assembled context dict, if available."""

    trace_id: str = ""
    """Correlation ID for tracing through the engine pipeline."""

    confidence_threshold: float = 0.85
    """Minimum confidence before escalation is triggered.

    Defaults to 0.85 for the Perception Engine per the Intelligence Runtime
    Canon (Observation thresholds require high reliability).
    """


# ── Engine Output ──────────────────────────────────────────────────────────────


@dataclass
class EngineOutput:
    """Canonical output contract for all Intelligence Engines.

    Every engine in the Intelligence Runtime produces this shape. The output
    carries not just the result payload, but also the computed confidence,
    a breakdown of confidence factors, and metadata about how the result
    was produced.

    Attributes:
        output_type: Type string describing the output (e.g., 'observation',
            'conclusion', 'plan').
        payload: Structured output data.
        confidence: Computed confidence score [0, 1].
        confidence_factors: Breakdown of the confidence computation, keyed by
            factor name with float values.
        deterministic: True if the result was computed locally without AI.
        trace_id: Correlation ID matching the input that produced this output.
        escalation_used: True if an AI inference provider was invoked.
        processing_time_ms: Wall-clock processing time in milliseconds.
    """

    output_type: str = ""
    """Type string describing the output (e.g., 'observation', 'conclusion')."""

    payload: dict[str, Any] = field(default_factory=dict)
    """Structured output data."""

    confidence: float = 0.0
    """Computed confidence score on [0, 1]."""

    confidence_factors: dict[str, float] = field(default_factory=dict)
    """Breakdown of the confidence computation, keyed by factor name."""

    deterministic: bool = True
    """True if the result was computed locally without AI assistance."""

    trace_id: str = ""
    """Correlation ID matching the input that produced this output."""

    escalation_used: bool = False
    """True if an AI inference provider was invoked during processing."""

    processing_time_ms: float = 0.0
    """Wall-clock processing time in milliseconds."""


# ── Escalation Result ──────────────────────────────────────────────────────────


@dataclass
class EscalationResult:
    """Result of escalating an input to an external AI inference provider.

    When deterministic computation yields confidence below the threshold,
    the escalation bridge packages the input into a prompt suitable for
    an AI provider (LLM, symbolic reasoner, etc.) and returns the result.

    Attributes:
        input_type: The original input type that required escalation.
        prompt: The prompt sent to the AI inference provider.
        context: Supporting context sent with the prompt.
        trace_id: Correlation ID matching the escalation chain.
    """

    input_type: str = ""
    """The original input type that required escalation."""

    prompt: str = ""
    """The prompt sent to the AI inference provider."""

    context: dict[str, Any] = field(default_factory=dict)
    """Supporting context sent with the prompt."""

    trace_id: str = ""
    """Correlation ID matching the escalation chain."""


# ── Observation ────────────────────────────────────────────────────────────────


@dataclass
class Observation:
    """A structured observation produced by the Perception Engine.

    Observations are the fundamental perceptual unit in the SHUNYA Intelligence
    Runtime. Every raw signal from the world is transformed through the
    perception pipeline (validate → enrich → classify → prioritise) into an
    Observation that downstream engines can consume.

    Each observation carries a deterministic confidence score derived from
    source reliability, timeliness, and classification certainty.

    Attributes:
        observation_id: Globally unique identifier (UUID v7).
        input_type: The classified InputType of the raw signal.
        payload: The validated and enriched payload data.
        source_metadata: Source provenance metadata from enrichment.
        priority: Assigned priority level.
        confidence: Deterministic confidence score [0, 1].
        trace_id: Correlation ID for tracing through the pipeline.
        status: Current lifecycle status of the observation.
        classification_rules: List of rule identifiers that matched during
            classification, for auditability.
        created_at: ISO-8601 timestamp of when the observation was created.
        processed_at: ISO-8601 timestamp of when observation processing
            completed, or None if still in progress.
        metadata: Extensible metadata container.
    """

    observation_id: str = ""
    """Globally unique identifier (UUID v7)."""

    input_type: str = InputType.UNKNOWN.value
    """The classified InputType of the raw signal."""

    payload: dict[str, Any] = field(default_factory=dict)
    """The validated and enriched payload data."""

    source_metadata: SourceMetadata = field(default_factory=SourceMetadata)
    """Source provenance metadata from the enrichment phase."""

    priority: str = PerceptionPriority.NORMAL.value
    """Assigned priority level."""

    confidence: float = 0.0
    """Deterministic confidence score on [0, 1]."""

    trace_id: str = ""
    """Correlation ID for tracing through the pipeline."""

    status: str = ObservationStatus.CAPTURED.value
    """Current lifecycle status of the observation."""

    classification_rules: list[str] = field(default_factory=list)
    """List of rule identifiers matched during classification."""

    created_at: str = field(default_factory=_now_iso)
    """ISO-8601 timestamp of when the observation was created."""

    processed_at: str | None = None
    """ISO-8601 timestamp of when processing completed, or None."""

    metadata: dict[str, Any] = field(default_factory=dict)
    """Extensible metadata container."""

    def to_dict(self) -> dict[str, Any]:
        """Serialize the observation to a plain dictionary.

        Returns:
            A JSON-serializable dict representation.
        """
        return {
            "observation_id": self.observation_id,
            "input_type": self.input_type,
            "payload": dict(self.payload),
            "source_metadata": {
                "source_engine": self.source_metadata.source_engine,
                "source_type": self.source_metadata.source_type,
                "source_reliability": self.source_metadata.source_reliability,
                "captured_at": self.source_metadata.captured_at,
                "received_at": self.source_metadata.received_at,
            },
            "priority": self.priority,
            "confidence": self.confidence,
            "trace_id": self.trace_id,
            "status": self.status,
            "classification_rules": list(self.classification_rules),
            "created_at": self.created_at,
            "processed_at": self.processed_at,
            "metadata": dict(self.metadata),
        }
