"""
SHUNYA — Reflection Engine Models

Defines the data structures for outcome reflection: anomaly detection,
success scoring, improvement signal categorization, and reflection records.

Implements the Reflection contracts defined in:
    - docs/canon/INTELLIGENCE_RUNTIME_CANON.md §10 (Reflection Engine)
    - docs/canon/07_ai_canon.md §11 (Evaluator Engine)

Reflection Flow:
    1. Compare outcome vs expected
    2. Detect anomalies (threshold-based)
    3. Compute success score
    4. Identify improvement signals
    5. Log reflection record
    6. Route signals to Learning Engine
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any

# ── Timestamp helper ───────────────────────────────────────────────────────────


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


# ── AnomalySeverity ────────────────────────────────────────────────────────────


class AnomalySeverity(str, Enum):
    """Severity levels for detected anomalies.

    Determines the urgency and escalation path for an anomaly.
    """

    INFO = "info"
    """Informational anomaly — no action needed."""
    WARNING = "warning"
    """Minor deviation — should be monitored."""
    ERROR = "error"
    """Significant deviation — requires investigation."""
    CRITICAL = "critical"
    """Severe deviation — requires immediate attention."""


# ── ImprovementSignalCategory ──────────────────────────────────────────────────


class ImprovementSignalCategory(str, Enum):
    """Categories for improvement signals routed to the Learning Engine.

    Each signal is categorized so the Learning Engine can apply the
    appropriate consolidation strategy.
    """

    PROCESS = "process"
    """Improvement in the decision or execution process."""
    KNOWLEDGE = "knowledge"
    """Missing or incorrect knowledge identified."""
    REASONING = "reasoning"
    """Reasoning quality or approach improvement."""
    TIMING = "timing"
    """Timing-related improvement (too early/late)."""
    COMMUNICATION = "communication"
    """Communication or handoff improvement needed."""
    EVIDENCE = "evidence"
    """Evidence quality or sufficiency improvement."""
    GOVERNANCE = "governance"
    """Policy or governance improvement needed."""
    TOOL = "tool"
    """Tool or integration improvement needed."""
    OTHER = "other"
    """Uncategorized improvement signal."""


# ── Anomaly ────────────────────────────────────────────────────────────────────


@dataclass
class Anomaly:
    """A detected anomaly from outcome comparison.

    Anomalies represent deviations between expected and actual outcomes
    that exceed defined thresholds. Each anomaly carries severity,
    description, and actionable details.
    """

    anomaly_id: str = ""
    """Unique identifier for this anomaly."""

    field: str = ""
    """The field or dimension where the anomaly was detected."""

    expected_value: Any = None
    """The expected value for comparison."""

    actual_value: Any = None
    """The actual observed value."""

    deviation: float = 0.0
    """Numeric deviation (absolute or percentage)."""

    severity: AnomalySeverity = AnomalySeverity.INFO
    """Severity level of this anomaly."""

    description: str = ""
    """Human-readable description of the anomaly."""

    threshold: float = 0.0
    """The threshold that was exceeded."""


# ── ImprovementSignal ──────────────────────────────────────────────────────────


@dataclass
class ImprovementSignal:
    """A structured improvement signal for the Learning Engine.

    Generated by the Reflection Engine when an outcome reveals an
    opportunity for improvement. Each signal includes categorization,
    context, and priority for the Learning Engine.
    """

    signal_id: str = ""
    """Unique identifier for this signal."""

    category: ImprovementSignalCategory = ImprovementSignalCategory.OTHER
    """Category of improvement."""

    description: str = ""
    """What should be improved."""

    detail: str = ""
    """Detailed analysis of the improvement opportunity."""

    priority: int = 0
    """Priority (higher = more urgent, range 0-10)."""

    source_reflection_id: str = ""
    """Reflection record ID that generated this signal."""

    context: dict[str, Any] = field(default_factory=dict)
    """Additional context for the Learning Engine."""


# ── OutcomeComparison ──────────────────────────────────────────────────────────


@dataclass
class OutcomeComparison:
    """Result of comparing expected vs actual outcomes.

    Captures the comparison for each evaluated dimension, including
    the deviation magnitude and whether it falls within tolerance.
    """

    dimension: str = ""
    """The dimension being compared (e.g., 'cost', 'timing', 'quality')."""

    expected: Any = None
    """Expected value for this dimension."""

    actual: Any = None
    """Actual observed value for this dimension."""

    deviation: float = 0.0
    """Absolute deviation between expected and actual."""

    deviation_pct: float = 0.0
    """Percentage deviation (0.0 = perfect match, 1.0 = 100% off)."""

    within_tolerance: bool = False
    """Whether the deviation is within the acceptable tolerance."""

    tolerance: float = 0.0
    """Acceptable tolerance threshold for this dimension."""

    detail: str = ""
    """Human-readable explanation of this comparison."""


# ── SuccessScoreComponents ──────────────────────────────────────────────────────


@dataclass
class SuccessScoreComponents:
    """Breakdown of the success score computation.

    The overall success score is a weighted combination of individual
    dimension scores. This structure records the contribution of each
    dimension for transparency.
    """

    dimension_scores: dict[str, float] = field(default_factory=dict)
    """Score per dimension [0.0, 1.0].

    Example: {'accuracy': 0.95, 'timing': 0.80, 'cost': 0.60}
    """

    weights: dict[str, float] = field(default_factory=dict)
    """Weight per dimension (must sum to 1.0).

    Example: {'accuracy': 0.4, 'timing': 0.3, 'cost': 0.3}
    """

    overall_score: float = 0.0
    """Weighted combination of dimension scores [0.0, 1.0]."""


# ── ReflectionRecord ───────────────────────────────────────────────────────────


@dataclass
class ReflectionRecord:
    """A complete reflection record produced by the Reflection Engine.

    Each reflection evaluates the outcome of a decision or action and
    captures: outcome comparison results, detected anomalies, success
    score, and improvement signals for the Learning Engine.
    """

    reflection_id: str = ""
    """Globally unique identifier for this reflection (UUID v7)."""

    subject_id: str = ""
    """ObjectID of the decision, action, or plan being reflected on."""

    subject_type: str = ""
    """Type of the subject (e.g., 'decision', 'plan', 'action')."""

    subject_label: str = ""
    """Human-readable label of the subject."""

    trace_id: str = ""
    """Correlation ID for tracing across the intelligence runtime."""

    expected_outcome: dict[str, Any] = field(default_factory=dict)
    """The expected outcome that was defined before execution.

    Keys represent outcome dimensions (e.g., 'cost', 'timing', 'status').
    """

    actual_outcome: dict[str, Any] = field(default_factory=dict)
    """The actual observed outcome after execution.

    Keys should match expected_outcome for direct comparison.
    """

    comparisons: list[OutcomeComparison] = field(default_factory=list)
    """Per-dimension comparison results."""

    success_score: float = 0.0
    """Overall success score [0.0, 1.0]."""

    success_score_components: SuccessScoreComponents | None = None
    """Breakdown of the success score computation."""

    anomalies: list[Anomaly] = field(default_factory=list)
    """Anomalies detected during comparison."""

    improvement_signals: list[ImprovementSignal] = field(default_factory=list)
    """Improvement signals generated from this reflection."""

    confidence: float = 0.0
    """Confidence in this reflection's analysis [0.0, 1.0]."""

    escalated: bool = False
    """Whether this reflection triggered an escalation."""

    timestamp: str = field(default_factory=_now_iso)
    """ISO-8601 timestamp of when the reflection was created."""

    metadata: dict[str, Any] = field(default_factory=dict)
    """Extensible metadata container."""

    def __post_init__(self) -> None:
        """Auto-generate reflection_id if missing."""
        if not self.reflection_id:
            from core.kernel.types import generate_uuid7
            object.__setattr__(self, "reflection_id", generate_uuid7())

    @property
    def has_anomalies(self) -> bool:
        """Whether any anomalies were detected.

        Returns:
            True if the anomalies list is non-empty.
        """
        return len(self.anomalies) > 0

    @property
    def has_improvement_signals(self) -> bool:
        """Whether any improvement signals were generated.

        Returns:
            True if the improvement_signals list is non-empty.
        """
        return len(self.improvement_signals) > 0


# ── Default Weights ────────────────────────────────────────────────────────────


DEFAULT_REFLECTION_WEIGHTS: dict[str, float] = {
    "accuracy": 0.30,
    "completeness": 0.20,
    "timing": 0.15,
    "efficiency": 0.15,
    "quality": 0.20,
}
"""Default dimension weights for success score computation.

These weights are used when no custom weights are provided. They
sum to 1.0.
"""


DEFAULT_ANOMALY_THRESHOLDS: dict[str, float] = {
    "info": 0.10,
    "warning": 0.25,
    "error": 0.50,
    "critical": 0.75,
}
"""Default deviation thresholds for anomaly severity levels.

A deviation exceeding the threshold triggers an anomaly of that
severity. For example, a 30% deviation exceeds the 'warning'
threshold (0.25) but not 'error' (0.50).
"""